"""Add config_stage.side_dwor_multiplier

Revision ID: 0006
Revises: 0005
Create Date: 2018-09-21 15:35:27.616534

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('side_dwor_multiplier', sa.Integer(), nullable=True))  # noqa

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_stage', schema=None) as batch_op:
        batch_op.drop_column('side_dwor_multiplier')

    # ### end Alembic commands ###
